# Generated by Django 4.0.2 on 2022-04-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_like_post_like_alter_profile_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.IntegerField(),
        ),
    ]
