# Generated by Django 4.0.2 on 2022-04-03 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creator_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
