# Generated by Django 4.0.2 on 2022-04-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_post_creator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creator_id',
            new_name='user',
        ),
    ]
