# Generated by Django 4.0.2 on 2022-04-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_profile_follower_profile_follower_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
