# Generated by Django 4.0.2 on 2022-04-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_remove_profile_follower_profile_follower_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-timestamp',)},
        ),
    ]
