# Generated by Django 4.0.2 on 2022-04-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_profile_user_alter_profile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
