# Generated by Django 4.0.2 on 2022-04-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
