# Generated by Django 4.0.2 on 2022-04-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0029_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
